apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted RW by ONE node only - forces scheduling of pods on one node
    # - ReadOnlyMany # Can be mounted RO by many nodes
    # - ReadWriteMany # Can be mounted RW by many nodes
    # - ReadWriteOncePod # Can be mounted RW by a single Pod
  resources:
    # Requests are not guaranteed
    requests:
      storage: 500Mi
